#!/usr/bin/env python3
"""Factor Lab Phase 2 rank score and factor score computation.

This command reads the daily raw metric snapshot generated by Phase 1,
converts each metric into a 0-100 rank score, then combines metric rank scores
into the seven Factor Lab factor scores.
"""

from __future__ import annotations

import argparse
import json
import math
import sqlite3
import sys
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from backfill_factor_lab_phase0 import (  # noqa: E402
    TaskStats,
    connect_db,
    ensure_schema,
    log_progress,
    log_step,
    resolve_db_path,
    utc_now,
)
TASK_TYPE_FACTOR_SCORE_COMPUTE = "factor_score_compute"
TASK_STATUS_RUNNING = "running"
TASK_STATUS_SUCCESS = "success"
TASK_STATUS_FAILED = "failed"


@dataclass(frozen=True)
class MetricSpec:
    key: str
    column: str
    lower_better: bool
    replace_negative_with_max_positive: bool = False


@dataclass(frozen=True)
class FactorComponent:
    metric_key: str
    weight: float


@dataclass(frozen=True)
class FactorSpec:
    key: str
    output_column: str
    components: tuple[FactorComponent, ...]


METRICS: tuple[MetricSpec, ...] = (
    MetricSpec("pe", "pe", True, True),
    MetricSpec("pb", "pb", True, True),
    MetricSpec("ps", "ps", True, True),
    MetricSpec("dividend_yield", "dividend_yield", False),
    MetricSpec("earning_growth", "earning_growth", False),
    MetricSpec("revenue_growth", "revenue_growth", False),
    MetricSpec("performance_1y", "performance_1y", False),
    MetricSpec("roe", "roe", False),
    MetricSpec("fcf_margin", "fcf_margin", False),
    MetricSpec("asset_to_equity", "asset_to_equity", True, True),
    MetricSpec("momentum_1m", "momentum_1m", False),
    MetricSpec("market_cap", "market_cap", True, True),
    MetricSpec("volatility_1m", "volatility_1m", True, True),
    MetricSpec("beta_1y", "beta_1y", True, True),
)

FACTORS: tuple[FactorSpec, ...] = (
    FactorSpec("value", "value_score", (FactorComponent("pe", 0.4), FactorComponent("pb", 0.4), FactorComponent("ps", 0.2))),
    FactorSpec("dividend_yield", "dividend_yield_score", (FactorComponent("dividend_yield", 1.0),)),
    FactorSpec("growth", "growth_score", (FactorComponent("earning_growth", 0.5), FactorComponent("revenue_growth", 0.3), FactorComponent("performance_1y", 0.2))),
    FactorSpec("quality", "quality_score", (FactorComponent("roe", 0.35), FactorComponent("fcf_margin", 0.33), FactorComponent("asset_to_equity", 0.32))),
    FactorSpec("momentum", "momentum_score", (FactorComponent("performance_1y", 0.7), FactorComponent("momentum_1m", 0.3))),
    FactorSpec("size", "size_score", (FactorComponent("market_cap", 1.0),)),
    FactorSpec("low_volatility", "low_volatility_score", (FactorComponent("volatility_1m", 0.4), FactorComponent("beta_1y", 0.6))),
)

RANK_COLUMNS = [f"{metric.key}_rank_score" for metric in METRICS]
FACTOR_COLUMNS = [factor.output_column for factor in FACTORS]


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Factor Lab Phase 2 rank score and factor score computation")
    parser.add_argument("--db", default="", help="pumpkin.db 路径；默认自动查找 data/pumpkin.db")
    parser.add_argument("--snapshot-date", default="", help="快照交易日 YYYY-MM-DD；默认取本地最新交易日")
    parser.add_argument("--write", action="store_true", help="实际写入 factor_rank_scores/factor_scores；默认 dry-run")
    parser.add_argument("--progress-interval", type=int, default=500, help="每处理多少只股票输出一次进度")
    return parser.parse_args(argv)


def safe_number(value: Any) -> Optional[float]:
    if value is None:
        return None
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    if math.isnan(number) or math.isinf(number):
        return None
    return number


def insert_task_run(conn: sqlite3.Connection, run_id: str, args: argparse.Namespace) -> None:
    conn.execute(
        """
        INSERT OR REPLACE INTO factor_task_runs
        (id, task_type, snapshot_date, status, started_at, total_count, success_count, failed_count, skipped_count, params_json, summary_json, error_message)
        VALUES (?, ?, ?, ?, ?, 0, 0, 0, 0, ?, '{}', '')
        """,
        (run_id, TASK_TYPE_FACTOR_SCORE_COMPUTE, args.snapshot_date, TASK_STATUS_RUNNING, utc_now(), json.dumps(vars(args), ensure_ascii=False, default=str)),
    )
    conn.commit()


def finish_task_run(conn: sqlite3.Connection, run_id: str, status: str, stats: TaskStats, summary: dict[str, Any], error: str = "") -> None:
    conn.execute(
        """
        UPDATE factor_task_runs
        SET status = ?, finished_at = ?, total_count = ?, success_count = ?, failed_count = ?, skipped_count = ?, summary_json = ?, error_message = ?
        WHERE id = ?
        """,
        (status, utc_now(), stats.total, stats.success, stats.failed, stats.skipped, json.dumps(summary, ensure_ascii=False), error, run_id),
    )
    conn.commit()


def latest_factor_snapshot_date(conn: sqlite3.Connection) -> str:
    row = conn.execute("SELECT MAX(snapshot_date) FROM factor_snapshots").fetchone()
    return row[0] if row and row[0] else ""


def load_snapshot_rows(conn: sqlite3.Connection, snapshot_date: str) -> list[dict[str, Any]]:
    metric_select = ", ".join(metric.column for metric in METRICS)
    rows = conn.execute(
        f"""
        SELECT snapshot_date, code, symbol, name, is_new_stock, close_price, {metric_select}
        FROM factor_snapshots
        WHERE snapshot_date = ?
        ORDER BY code ASC
        """,
        (snapshot_date,),
    ).fetchall()
    result: list[dict[str, Any]] = []
    keys = ["snapshot_date", "code", "symbol", "name", "is_new_stock", "close_price", *[metric.key for metric in METRICS]]
    for row in rows:
        result.append(dict(zip(keys, row)))
    return result


def load_industries(conn: sqlite3.Connection) -> dict[str, str]:
    industries: dict[str, str] = {}
    try:
        rows = conn.execute("SELECT code, industry_name FROM factor_security_industries WHERE industry_name <> ''").fetchall()
        for code, industry_name in rows:
            industries[str(code)] = str(industry_name or "")
    except sqlite3.Error:
        pass
    if industries:
        return industries
    try:
        rows = conn.execute("SELECT code, industry_name FROM company_profiles WHERE industry_name <> ''").fetchall()
        for code, industry_name in rows:
            industries[str(code)] = str(industry_name or "")
    except sqlite3.Error:
        pass
    return industries


def adjusted_metric_value(value: float, max_positive: Optional[float], spec: MetricSpec) -> float:
    if spec.replace_negative_with_max_positive and value < 0 and max_positive is not None:
        return max_positive
    return value


def compute_metric_rank_scores(rows: list[dict[str, Any]], spec: MetricSpec) -> dict[str, float]:
    raw_values: list[tuple[str, float]] = []
    for row in rows:
        value = safe_number(row.get(spec.key))
        if value is None:
            continue
        raw_values.append((str(row["code"]), value))
    if not raw_values:
        return {}
    positive_values = [value for _, value in raw_values if value > 0]
    max_positive = max(positive_values) if positive_values else None
    sortable = [(code, adjusted_metric_value(value, max_positive, spec)) for code, value in raw_values]
    sortable.sort(key=lambda item: (item[1], item[0]), reverse=not spec.lower_better)
    total = len(sortable)
    scores: dict[str, float] = {}
    previous_value: Optional[float] = None
    current_rank = 0
    for index, (code, value) in enumerate(sortable, start=1):
        if previous_value is None or value != previous_value:
            current_rank = index
            previous_value = value
        scores[code] = (total - current_rank + 1) / total * 100.0
    return scores


def weighted_score(rank_row: dict[str, Optional[float]], factor: FactorSpec) -> Optional[float]:
    numerator = 0.0
    denominator = 0.0
    for component in factor.components:
        score = rank_row.get(f"{component.metric_key}_rank_score")
        if score is None:
            continue
        numerator += score * component.weight
        denominator += component.weight
    if denominator <= 0:
        return None
    return numerator / denominator


def compute_scores(conn: sqlite3.Connection, snapshot_date: str, progress_interval: int) -> tuple[list[tuple[Any, ...]], list[tuple[Any, ...]], dict[str, int]]:
    rows = load_snapshot_rows(conn, snapshot_date)
    industries = load_industries(conn)
    log_step(f"phase2: 加载快照 {snapshot_date} 股票 {len(rows)} 条，行业映射 {len(industries)} 条")
    metric_scores = {spec.key: compute_metric_rank_scores(rows, spec) for spec in METRICS}
    coverage = {f"{key}_rank_score": len(scores) for key, scores in metric_scores.items()}
    now = utc_now()
    rank_rows: list[tuple[Any, ...]] = []
    factor_rows: list[tuple[Any, ...]] = []
    for idx, row in enumerate(rows, start=1):
        log_progress("phase2: 因子分计算进度", idx, len(rows), progress_interval)
        code = str(row["code"])
        rank_values: dict[str, Optional[float]] = {}
        for spec in METRICS:
            rank_values[f"{spec.key}_rank_score"] = metric_scores[spec.key].get(code)
        factor_values = {factor.output_column: weighted_score(rank_values, factor) for factor in FACTORS}
        rank_rows.append((snapshot_date, code, *[rank_values[column] for column in RANK_COLUMNS], now))
        factor_rows.append((
            snapshot_date,
            code,
            row.get("symbol") or "",
            row.get("name") or code,
            industries.get(code, ""),
            int(row.get("is_new_stock") or 0),
            safe_number(row.get("close_price")) or 0.0,
            *[factor_values[column] for column in FACTOR_COLUMNS],
            now,
        ))
    for factor in FACTORS:
        coverage[factor.output_column] = sum(1 for item in factor_rows if item[7 + FACTOR_COLUMNS.index(factor.output_column)] is not None)
    return rank_rows, factor_rows, coverage


def write_scores(conn: sqlite3.Connection, snapshot_date: str, rank_rows: list[tuple[Any, ...]], factor_rows: list[tuple[Any, ...]]) -> None:
    rank_placeholders = ", ".join(["?"] * (2 + len(RANK_COLUMNS) + 1))
    factor_placeholders = ", ".join(["?"] * (7 + len(FACTOR_COLUMNS) + 1))
    rank_columns = ", ".join(["snapshot_date", "code", *RANK_COLUMNS, "created_at"])
    factor_columns = ", ".join(["snapshot_date", "code", "symbol", "name", "industry", "is_new_stock", "close_price", *FACTOR_COLUMNS, "created_at"])
    conn.execute("BEGIN")
    try:
        conn.execute("DELETE FROM factor_rank_scores WHERE snapshot_date = ?", (snapshot_date,))
        conn.execute("DELETE FROM factor_scores WHERE snapshot_date = ?", (snapshot_date,))
        conn.executemany(f"INSERT INTO factor_rank_scores ({rank_columns}) VALUES ({rank_placeholders})", rank_rows)
        conn.executemany(f"INSERT INTO factor_scores ({factor_columns}) VALUES ({factor_placeholders})", factor_rows)
        conn.commit()
    except Exception:
        conn.rollback()
        raise


def run_phase2(conn: sqlite3.Connection, args: argparse.Namespace, run_id: str) -> TaskStats:
    rank_rows, factor_rows, coverage = compute_scores(conn, args.snapshot_date, args.progress_interval)
    stats = TaskStats(total=len(factor_rows), success=len(factor_rows), failed=0, skipped=0)
    summary = {"snapshot_date": args.snapshot_date, "rank_rows": len(rank_rows), "factor_rows": len(factor_rows), "coverage": coverage}
    log_step(f"phase2: 计算完成 rank_rows={len(rank_rows)} factor_rows={len(factor_rows)}")
    log_step(f"phase2: 覆盖情况 {json.dumps(coverage, ensure_ascii=False)}")
    if not args.write:
        stats.success = 0
        stats.skipped = len(factor_rows)
        print(f"[dry-run] {json.dumps(summary, ensure_ascii=False)}", flush=True)
        return stats
    write_scores(conn, args.snapshot_date, rank_rows, factor_rows)
    finish_task_run(conn, run_id, TASK_STATUS_SUCCESS, stats, summary)
    log_step(f"phase2: 写入 factor_rank_scores={len(rank_rows)} factor_scores={len(factor_rows)}")
    return stats


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    if args.progress_interval <= 0:
        raise ValueError("--progress-interval 必须大于 0")
    db_path = resolve_db_path(args.db)
    conn = connect_db(db_path)
    ensure_schema(conn)
    if not args.snapshot_date:
        args.snapshot_date = latest_factor_snapshot_date(conn)
    if not args.snapshot_date:
        print("failed: 本地 factor_snapshots 没有可用快照", file=sys.stderr)
        return 1
    run_id = str(uuid.uuid4())
    print(f"db={db_path}", flush=True)
    print(f"run_id={run_id}", flush=True)
    print("mode=dry-run" if not args.write else "mode=write", flush=True)
    if args.write:
        insert_task_run(conn, run_id, args)
    try:
        stats = run_phase2(conn, args, run_id)
        status = TASK_STATUS_SUCCESS if stats.failed == 0 else TASK_STATUS_FAILED
        print(f"summary={json.dumps({'total': stats.total, 'success': stats.success, 'failed': stats.failed, 'skipped': stats.skipped, 'snapshot_date': args.snapshot_date}, ensure_ascii=False)} status={status}", flush=True)
        return 0 if status == TASK_STATUS_SUCCESS else 1
    except Exception as exc:  # noqa: BLE001
        if args.write:
            finish_task_run(conn, run_id, TASK_STATUS_FAILED, TaskStats(), {}, str(exc))
        print(f"failed: {exc}", file=sys.stderr)
        return 1
    finally:
        conn.close()


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
